### ISSUE TITLE
nltk not in env.yml

### ISSUE THREAD

**Issue by zkokaja** [hvgazula/247-decoding#17]
Got error
```
Traceback (most recent call last):
  File "tfs_pickling.py", line 15, in <module>
    from nltk.stem import PorterStemmer
ModuleNotFoundError: No module named 'nltk'
```

**Comment by hvgazula** [comment]
Sorry about that. That's because I am using the default (to my directory)`torch-env`. I am unsure which one are you using.

**Comment by hvgazula** [comment]
https://github.com/orgs/hassonlab/projects/1#card-51458231

**Comment by hvgazula** [comment]
Never mind. The env.yml file is old and hasn't been updated in a while.

**Comment by hvgazula** [comment]
Done. Thanks for pointing it out.
